// AUTO-GENERATED by scripts/generate-plates.ts — do not edit by hand.
// Re-run with `npm run gen:plates` after changing prompts.

export const PLATE_IMAGES_BY_TITLE: Record<string, string> = {
  "Freckled laugh, golden hour": "plates/freckled-laugh-golden-hour.webp",
  "Tokyo neon, candid": "plates/tokyo-neon-candid.webp",
  "Soot and embers": "plates/soot-and-embers.webp",
  "Two suns setting": "plates/two-suns-setting.webp",
  "Noir on a rainy street": "plates/noir-on-a-rainy-street.webp",
  "Cyberpunk night market": "plates/cyberpunk-night-market.webp",
  "Iridescent dragon, fire": "plates/iridescent-dragon-fire.webp",
  "City inside a great tree": "plates/city-inside-a-great-tree.webp",
  "Ghibli forest, silver hair": "plates/ghibli-forest-silver-hair.webp",
  "Shinkai rain, shared umbrella": "plates/shinkai-rain-shared-umbrella.webp",
  "Smartwatch on marble": "plates/smartwatch-on-marble.webp",
  "Perfume and fresh flowers": "plates/perfume-and-fresh-flowers.webp",
  "Dewdrop on a spider web": "plates/dewdrop-on-a-spider-web.webp",
  "Storm-edge cliff": "plates/storm-edge-cliff.webp",
  "Misty dawn path": "plates/misty-dawn-path.webp",
  "Hyper-detail action figure": "plates/hyper-detail-action-figure.webp",
}
